// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCilOVyqa8vwOVKrzzdYpWd04RKUldvTY',
    appId: '1:1004816388523:web:96a50da023d988b56982ee',
    messagingSenderId: '1004816388523',
    projectId: 'chatapp2-56bd7',
    authDomain: 'chatapp2-56bd7.firebaseapp.com',
    storageBucket: 'chatapp2-56bd7.appspot.com',
    measurementId: 'G-8RPY33QF33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd34F5HVrTzjpIILQcRwjLIRNReaLM4j4',
    appId: '1:1004816388523:android:675ed771815e79356982ee',
    messagingSenderId: '1004816388523',
    projectId: 'chatapp2-56bd7',
    storageBucket: 'chatapp2-56bd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEPtruQg3lPgPebQVCXym3LyFwNdixJV8',
    appId: '1:1004816388523:ios:2eddc4eeab1683ab6982ee',
    messagingSenderId: '1004816388523',
    projectId: 'chatapp2-56bd7',
    storageBucket: 'chatapp2-56bd7.appspot.com',
    iosBundleId: 'com.example.chatappFinal',
  );
}
